### ISSUE TITLE
Support for WebGL platform?

### ISSUE THREAD

**Issue by kultie** [line/line-sdk-unity#11]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. LINE SDK version, Unity version, Android version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Hi, @kultie 

`line-sdk-unity` is now a wrapper for our native SKDs, which in turn are built for native apps for iOS and Android. It does not support WebGL as a target platform, and there is plan for it yet now.
