### ISSUE TITLE
Unity SDK still compatible with new Line SDK 5.0.0 or Line SDK ios 5.0.1? 

### ISSUE THREAD

**Issue by kultie** [line/line-sdk-unity#14]
When building release version of my apps, XCode show that target version of swift SDK is not supported (5.0), i'm using XCode10.1 support max 4.2. 
Are there any problem if i change the target version to 4.2? Do need to upgrade xcode to support swift sdk 5.0?

**Comment by onevcat** [comment]
On iOS, the underline LINE SDK for Swift should support either Swift 4.2 or Swift 5.0. So I think it should be totally fine to change the target version to 4.2.

**Comment by kultie** [comment]
Okay thanks for the confirmation
