### ISSUE TITLE
Module 'LineSDKObjC' not found

### ISSUE THREAD

**Issue by tearscry520** [line/line-sdk-unity#18]
I using unity **2019.3.10f1** and **Cocoapods**
Build iOS with target 10.0 minimum
But Xcode is build failed
Error Message 
`Module 'LineSDKObjC' not found`

My environment
Build from Unity 2019.3.10f1
XCode 11.4.1
Build target iOS 10.0
LineSDK 1.1.1

**Comment by ProfShih** [comment]
same issue here with Unity2019.2.8
Xcode 11.4.1

**Comment by tearscry520** [comment]
> same issue here with Unity2019.2.8
> Xcode 11.4.1

Hey
I change using Carthage build is success.
You can reference this https://developers.line.biz/en/docs/ios-sdk/swift/using-objc/#use-wrapper

**Comment by ProfShih** [comment]
haha I'm following that reference and I see your reply.
thanks for the indication, hope it works for me!

**Comment by ProfShih** [comment]
hey @tearscry520 
I followed the steps in the reference and still get the the same error ;-(
and I noticed that the name of the imported binary library in the build phase tab
is "LineSDKObjC.framework.framework", kinda wired. 

the .framework files in Build/iOS/ have identical names to the tutorial, but after importing 
the displayed name gets like that.

**Comment by tearscry520** [comment]
Sorry, My english is not good.
So I don't understand what you mean.

Could you give me a picture?

**Comment by tearscry520** [comment]
@ProfShih 
Sorry, My english is not good.
So I don't understand what you mean.

Could you give me a picture?

**Comment by Won-gyu** [comment]
I did ReimportAll my Unity project and built iOS. And the error's gone away.
