### ISSUE TITLE
error CS0619: 'PBXProject.GetUnityTargetName()' is obsolete

### ISSUE THREAD

**Issue by toduq** [line/line-sdk-unity#19]
## Is it a security issue?

No

## What did you do?

I am not an actual reporter, just escalate this issue.
https://www.line-community.me/question/5eb4e142851f7402cd9712aa

`PBXProject.GetUnityTargetName()` seems to be already removed,
https://docs.unity3d.com/ScriptReference/iOS.Xcode.PBXProject.GetUnityTargetName.html

but I found 2 usage in this project.
https://github.com/line/line-sdk-unity/search?q=GetUnityTargetName&unscoped_q=GetUnityTargetName

## What did you expect?

The obsoleted method call will be removed.

## What happened actually?

`PBXProject.GetUnityTargetName()` is used, and it caused an error.

## Your environment?

Ref : https://www.line-community.me/question/5eb4e142851f7402cd9712aa

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Thanks for reporting this. It is too back that this method is unavailable from Unity 2019.3. We will fix it soon.

**Comment by onevcat** [comment]
I am going to release a patch for it, so I am closing this issue now.

**Comment by toduq** [comment]
Thank you so much to quickly fix this issue! :tada:

**Comment by onevcat** [comment]
[Version 1.1.2](https://github.com/line/line-sdk-unity/releases/tag/1.1.2) was released to fix it.
