### ISSUE TITLE
Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig

### ISSUE THREAD

**Issue by Antivortex** [line/line-sdk-unity#28]
Hello.

We're getting this error on the attempt to login with {"profile", "openid"} scopes. 

Line app shows popup with this text
"Error
An unknown error occured"

Login callback onMatchedError returns error Message:
"login is canceled"

When I check the errors on ADB logcat, i see these exceptions at the moment when Login is called:

`11-03 18:41:33.027  2992  6578 E Parcel  : Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
11-03 18:41:33.027  2992  6578 E Parcel  : java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
11-03 18:41:33.027  2992  6578 E Parcel  :      at java.lang.Class.classForName(Native Method)
11-03 18:41:33.027  2992  6578 E Parcel  :      at java.lang.Class.forName(Class.java:453)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:2905)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2859)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2762)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3131)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:226)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.BaseBundle.getString(BaseBundle.java:1118)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.content.Intent.getStringExtra(Intent.java:7807)
11-03 18:41:33.027  2992  6578 E Parcel  :      at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:509)
11-03 18:41:33.027  2992  6578 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:454)
11-03 18:41:33.027  2992  6578 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1375)
11-03 18:41:33.027  2992  6578 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6295)
11-03 18:41:33.027  2992  6578 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6144)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
11-03 18:41:33.027  2992  6578 E Parcel  :      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4024)
11-03 18:41:33.027  2992  6578 E Parcel  :      at android.os.Binder.execTransact(Binder.java:705)
11-03 18:41:33.027  2992  6578 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
11-03 18:41:33.027  2992  6578 E Parcel  :      at java.lang.Class.classForName(Native Method)
11-03 18:41:33.027  2992  6578 E Parcel  :      at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
11-03 18:41:33.027  2992  6578 E Parcel  :      at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
11-03 18:41:33.027  2992  6578 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-03 18:41:33.027  2992  6578 E Parcel  :      ... 18 more
11-03 18:41:33.027  2992  6578 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-03 18:41:33.039  2992  3480 E Watchdog: !@Sync 26038 [2020-11-03 18:41:33.039]
11-03 18:41:33.806 11411 20842 E GOS:SeDex: failed to getSystemService()
11-03 18:41:33.806 11411 20842 E GOS:SeDex: mDesktopModeManager is null
11-03 18:41:33.806 11411 20842 E GOS:SeDex: mDesktopModeManager is null
11-03 18:41:33.823  2992  3689 E Parcel  : Class not found when unmarshalling: p0.a.a.a.t2.l.r0.a$b
11-03 18:41:33.823  2992  3689 E Parcel  : java.lang.ClassNotFoundException: p0.a.a.a.t2.l.r0.a$b
11-03 18:41:33.823  2992  3689 E Parcel  :      at java.lang.Class.classForName(Native Method)
11-03 18:41:33.823  2992  3689 E Parcel  :      at java.lang.Class.forName(Class.java:453)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:2905)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2859)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2762)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3131)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:226)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.BaseBundle.getString(BaseBundle.java:1118)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.content.Intent.getStringExtra(Intent.java:7807)
11-03 18:41:33.823  2992  3689 E Parcel  :      at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:509)
11-03 18:41:33.823  2992  3689 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:454)
11-03 18:41:33.823  2992  3689 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1375)
11-03 18:41:33.823  2992  3689 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6295)
11-03 18:41:33.823  2992  3689 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6144)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
11-03 18:41:33.823  2992  3689 E Parcel  :      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4024)
11-03 18:41:33.823  2992  3689 E Parcel  :      at android.os.Binder.execTransact(Binder.java:705)
11-03 18:41:33.823  2992  3689 E Parcel  : Caused by: java.lang.ClassNotFoundException: p0.a.a.a.t2.l.r0.a$b
11-03 18:41:33.823  2992  3689 E Parcel  :      at java.lang.Class.classForName(Native Method)
11-03 18:41:33.823  2992  3689 E Parcel  :      at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
11-03 18:41:33.823  2992  3689 E Parcel  :      at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
11-03 18:41:33.823  2992  3689 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-03 18:41:33.823  2992  3689 E Parcel  :      ... 18 more
11-03 18:41:33.823  2992  3689 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-03 18:41:33.887 20017 20858 E GameTools: GameToolsIntentService : KillMySelf request ignored
11-03 18:41:34.329 19228 19228 E ViewRootImpl: sendUserActionEvent() returned.
11-03 18:41:34.450  2992  3061 E WindowManager: win=Window{9ad7f88 u0 jp.naver.line.android/jp.naver.line.android.urlscheme.service.oauth.OAuthWebLoginServiceActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:553 com.android.server.wm.DisplayContent.lambda$-com_android_server_wm_DisplayContent_21292:465
11-03 18:41:41.972 20870 20870 E Zygote  : isWhitelistProcess - Process is Whitelisted
11-03 18:41:41.973 20870 20870 E libpersona: scanKnoxPersonas`

Package name, signature and channel ID seem to be in place. How can we get more detailed log on why the request was cancelled? Is ClassNotFoundException could be the cause for it, or it's just only about some configuration missing?

I can also provide our channel ID if you need it.

Thank you.

**Comment by plateaukao** [comment]
Hi, @Antivortex 
Please help to report the issue by using the issue template, with more necessary details, such as what unity version you are using, and did you turn on proguard for Android. 

I'll close the issue for now. When you provided information with the issue template, please re-open it again. Thank you.
