### ISSUE TITLE
Get user's email from IDToken?

### ISSUE THREAD

**Issue by xuancelestial** [line/line-sdk-unity#31]
Is there anyway I could get user's email from this SDK?

## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. LINE SDK version, Unity version, Android version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Hi,

Yes. You can get the `IdTokenRaw` from the [`AccessToken`](https://github.com/line/line-sdk-unity/blob/master/LINE_SDK_Unity/Assets/LineSDK/Model/AccessToken.cs#L71) in the login result. However, this is a raw ID token string ([JWT](https://datatracker.ietf.org/doc/html/draft-jones-json-web-token-10)) without parsed, so you need to convert it to a JSON and get [its `email` field](https://developers.line.biz/en/reference/line-login/#verify-id-token) manually. This is not convenient for now and we will add to our backlog! Before we can have a built-in way to parse it, you can try to find some other library or parse it yourself (Basically it is a base64 URL encoded string, and you can find a few existing libraries for this purpose.)

The detailed steps:

- Apply for OpenID and email permission in the developer portal console:

![](https://user-images.githubusercontent.com/1019875/120408920-edf39980-c38a-11eb-99d8-dc07f1d57a07.png)

- Login with necessary scopes:

```csharp
var scopes = new string[] {"profile", "openid", "email"};
LineSDK.Instance.Login(scopes, result => {
  //...
}
```

- Convert the raw string and get email

```csharp
var raw = result.AccessToken.IdTokenRaw; // Remember to check null.
var jwt = SomeJWTLib.convertToDictionary(raw);
var email = jwt["email"]; // Remember to check null. Users can choose not allow you access the email.
```

**Comment by xuancelestial** [comment]
Thank you! will try it out
