### ISSUE TITLE
Bot_prompt did not work in my project !

### ISSUE THREAD

**Issue by chenZhenTom** [line/line-sdk-unity#32]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> I use Login Function from LineSDK with LoginOption In this picture below
![image](https://user-images.githubusercontent.com/40220526/120936285-b04f9180-c739-11eb-9c4d-f88b4787353d.png)

And I've set Linked OA in my  linelogin Channel
![image](https://user-images.githubusercontent.com/40220526/120936404-1dfbbd80-c73a-11eb-9f8d-2c8e8a85dea6.png)

## What did you expect?

> When use Line Login, the add linebot as a friend option show up

## What happened actually?

> 
but when the authorization screen show up. the option to add my linebot as a friend's option didn't show. 
![image](https://user-images.githubusercontent.com/40220526/120936486-96627e80-c73a-11eb-87b0-f31dfaf8f758.png)

Am I do something wrong? Thanks a lot

Or I think is because my lineBot is not an official account, so that this doesn't work?

## Your environment?

>  
LINE SDK  : I think is the newest version, 
Unity version : 2019.4.19f1, 
On Android device

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
@chenZhenTom

Hi,

Can you let me know your channel ID? So we can check the status and try to find what can cause this. Thanks!

**Comment by onevcat** [comment]
And it would be also nice if you can reproduce this issue one more time, and tell me the date/time of your action. So we can find the related log faster.

**Comment by chenZhenTom** [comment]
Hi ,thanks for replay

my login channel Id is 1655953068
and I try login again at 2021/6/7 12.36 pm

**Comment by onevcat** [comment]
@chenZhenTom This seems to be a bug inside the SDK wrapper. A fix has been applied in #33 and we are going to perform some final checks before a new release can be made. Please stay tuned!

Sorry for the inconvenience!

**Comment by chenZhenTom** [comment]
Thanks

I am looking forward to the new release.

**Comment by onevcat** [comment]
@chenZhenTom 

Hi,

We are glad to say that 1.1.6 was just released for this issue. You can now upgrade it from [the release page](https://github.com/line/line-sdk-unity/releases/tag/1.1.6). It also contains some project setting upgrade and a modern format of new `build.gradle` template suggested by Unity. 

If you are using your own gradle file, I suggest you making sure to backup it before you import the new package. Or, if you can just upgrade the `line-sdk-unity-wrapper-release.aar` file under `Plugins/Android` to get the fix, which should be the only noticeable change in this release.

Please feel free to let me know if you need any other help! Sorry for the inconvenience it might cause!
