### ISSUE TITLE
how to share and get all friend ids？

### ISSUE THREAD

**Issue by RainforestPie** [line/line-sdk-unity#41]
Hello, I have less experience in accessing the SDK, and now I want to obtain a list of friend ids and realize the sharing function. It seems that there is no such interface in the 
line-sdk-unity. What should I do? Do I need to extend the SDK by myself? Thanks for the answer~

**Comment by onevcat** [comment]
Hi,

Currently the friends list getting and sharing is only provided as a feature for LINE Technology Partner program and not yet contained in the Unity SDK here. If you already have required permissions to those features and need to access them in Unity, currently you have to extend the SDK to call related APIs your own.

Please also consider to [send a feature request](https://www.linebiz.com/jp/contact/) if you are in the Technology Partner program.

**Comment by RainforestPie** [comment]
The reply was so quick.
I searched the Internet for a long time yesterday and didn’t have a clue. 

Thank you very much for pointing the direction! I'll try it. ; )

**Comment by RainforestPie** [comment]
> Hi,
> 
> Currently the friends list getting and sharing is only provided as a feature for LINE Technology Partner program and not yet contained in the Unity SDK here. If you already have required permissions to those features and need to access them in Unity, currently you have to extend the SDK to call related APIs your own.
> 
> Please also consider to [send a feature request](https://www.linebiz.com/jp/contact/) if you are in the Technology Partner program.

@onevcat Hi, now I have implemented the Line sharing function. But the friend list cannot be obtained yet, and there is doubt.

As far as I know, the official Line account can get the id list of Follwer, but the official account type I created is Unverified, and because the area is outside the scope of application, I cannot apply for a verified account. This is probably the way you call team partner.This way is temporarily unworkable for me.

https://help2.line.me/official_account/web/categoryId/20006326/pc?lang=en
![image](https://user-images.githubusercontent.com/53807655/148530745-0ee8604e-f087-4916-abe5-11e1f47f0ebf.png)

On the other hand, what I want to get is **the list of friend ids of my personal account**. I have not found the relevant interface. Is there a way? 

Similar to the problems encountered by others below:

[Get Friend List with LINE Unity SDK](https://www.line-community.me/en/question/5e95fd1b851f7402cd969ace/get-friend-list-with-line-unity-sdk
)
![image](https://user-images.githubusercontent.com/53807655/148530844-eeede4fc-2645-4c7f-acb9-2f36e5de4b4e.png)

[How to get friend's list and friend's profile on line api ？](https://stackoverflow.com/questions/45158199/how-to-get-friends-list-and-friends-profile-on-line-api-using-php-or-shell-scr/45502990#45502990?newreg=fadc9c9456d84970830a587d43e1ee47
)

Thanks for answering~

**Comment by RainforestPie** [comment]
I realized that the Line SDK should not be able to get the user's friend list. 

Different from Facebook and Twitter (their SDK can get the Followers and Following lists, which are public), Line is more like Wechat, and its friend relationship data is more private and important.

I think it should be like this. Thanks a lot~
