### ISSUE TITLE
Only supports Unity 2019.3, other new versions 2019.4 (inclusive) and above, cannot be used

### ISSUE THREAD

**Issue by szjia** [line/line-sdk-unity#43]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com ).

## What did you do?

Using the LINE SDK in versions other than Unity 2019.3

## What did you expect?

Versions other than Unity 2019.3 use the LINE SDK

## What happened actually?

Unable to activate LINE verification function

## What happened actually?

I can generate APK normally in versions other than unity 2019.3, but the verification screen cannot be jumped out after executing the program

## Your environment?

LINE SDK version 1.1.6
Unity version can only be used in 2019.3, other versions cannot be used
Android version 10
iOS version, etc. 15

## Sample project

https://drive.google.com/file/d/1EUZvjr43hU_ryYySo5FVy1l8aD8-_iX1/view?usp=sharing

**Comment by onevcat** [comment]
@szjia Thanks for reporting this.

Through the logs, it seems that the Gson cannot be found:

```
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;
 	at com.linecorp.linesdk.unitywrapper.LineSdkWrapper.<init>(LineSdkWrapper.kt:21)
 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
 	at android.os.Handler.dispatchMessage(Handler.java:103)
 	at android.os.Looper.loop(Looper.java:223)
 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
```

If setup correctly, this dependency should be added through the [`mainTemplate` file here](https://github.com/line/line-sdk-unity/blob/master/LINE_SDK_Unity/Assets/Plugins/Android/mainTemplate.gradle#L38). So I guess there are some reasons that the dependency is not added in the new versions.

I will check it in detail to see a better way to add dependencies. 
Meanwhile, you can also try to check if it is possible to add the related dependencies then it should work back to the normal way.

**Comment by onevcat** [comment]
The new template gradle file should solve this issue (#44) and a new version 1.2.0 was released for this. I am going to close this issue now.

Please feel free to let us know if there is any other issues! Thank you.
