### ISSUE TITLE
LineSDK.Instance.CurrentAccessToken throws an exception on Android.

### ISSUE THREAD

**Issue by ynaoto** [line/line-sdk-unity#48]
## Is it a security issue?

No

## What did you do?

Access LineSDK.Instance.CurrentAccessToken on Android. Works well on iOS.

## What did you expect?

Get acccess token or null.

## What happened actually?

"UnityEngine.AndroidJavaException: java.util.NoSuchElementException: response data is null. Please check result by isSuccess before."

## Your environment?

Unity 2021.3.14f1, LINE SDK 1.2.0, Android.

## Sample project

N/A.

**Comment by ynaoto** [comment]
Additional info.  LineSDK.Instance.Login func worked.

**Comment by onevcat** [comment]
@ynaoto Thanks for reporting this. May I know did you perform a login before accessing the `CurrentAccessToken` or not? And after you do a successful login, does this issue still persist?

@plateaukao Hi, any idea on this? In either way, accessing the token should not throw an exception.

**Comment by ynaoto** [comment]
@onevcat Thanks for your quick response.

> did you perform a login before accessing the CurrentAccessToken or not?

I accessed the CurrentAccessToken BEFORE a login. (on iOS returns null, Android throws an exception)

> after you do a successful login, does this issue still persist?

No exception after succesful login.

**Comment by onevcat** [comment]
This is fixed in #49 and I will prepare a tag for it soon.

Thanks again for reporting this!

**Comment by onevcat** [comment]
[Version 1.2.1](https://github.com/line/line-sdk-unity/releases/tag/1.2.1) was released for this.
