### ISSUE TITLE
Regarding the status of Privacy Manifest compatibility.

### ISSUE THREAD

**Issue by nakazawam2023** [line/line-sdk-unity#65]
We have subscribed to the channel in our app, and in our development, we are using the Line SDK for Unity. 
However, we have noticed that the latest version available, 1.3.2, does not seem to have PrivacyManifest support.

It appears that Line SDK for iOS Swift is already compatible, but I would like to know when Line SDK for Unity will be supported (an estimated timeframe would be fine),
 if it is possible to provide that information.

Thank you in advance.

**Comment by onevcat** [comment]
Thanks for reporting this.

I will try to add it in another update soon. Stay tuned!

**Comment by onevcat** [comment]
Released in line-sdk-unity version 1.3.3.
