### ISSUE TITLE
Compile fails with Android platform build

### ISSUE THREAD

**Issue by kshoji** [line/line-sdk-unity#8]
## Is it a security issue?

NO.

## What did you do?

Compile with Android platform build on Unity Editor.

## What did you expect?

Compile succeeds with Android build.

## What happened actually?

Compile fails with Android build.
The error message is:
```
Assets/LineSDK/Editor/Carthage/CarthageInstalling.cs(22,19): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?
```

This file must be specified with `#if UNITY_IOS` ... `#endif`
https://github.com/line/line-sdk-unity/blob/master/LINE_SDK_Unity/Assets/LineSDK/Editor/Carthage/CarthageInstalling.cs

## Your environment?

* LINE SDK for Unity 1.0.1
* Unity 2017.4.29f1
* Android minSdkVersion 21, compileSdkVersion 28, and targetSdkVersion 28

## Sample project

none.

**Comment by onevcat** [comment]
@kshoji Thanks for reporting this.

May I know the system you are using for running Unity, is it Windows or macOS?

**Comment by onevcat** [comment]
Can you try whether this PR (https://github.com/line/line-sdk-unity/pull/9) could fix your issue? Thank you!

**Comment by kshoji** [comment]
@onevcat 

> May I know the system you are using for running Unity, is it Windows or macOS?
I'm using Unity on macOS.

And, the PR #9 fixed this issue. Thanks!

**Comment by onevcat** [comment]
Thanks for your feedback! I will release a new version soon for this.
